# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TicketHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QObject
from PyQt5.QtWidgets import QApplication, QMessageBox
from datetime import datetime
import schedule
import win32clipboard
import os
from stylesTicket import AddStyles



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        self.add_styles_instance = AddStyles()




        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 878)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("background: #141414;\n""\n""\n""")

        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("border-radius: 0px;\n""background: #221f41;\n""")
        
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.op_left = QtWidgets.QFrame(self.content)
        self.op_left.setMaximumSize(QtCore.QSize(200, 16777215))
        self.op_left.setStyleSheet("#op_left QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#op_left QPushButton {\n"
"    font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background: #141414;\n"
"}\n"
"#op_left QPushButton:hover {\n"
"    background-color: #58fe81;\n"
"    color: black;\n"
"    border: 2px solid rgb(60,60,60);\n"
"}\n"
"#op_left QPushButton:focus {\n"
"    background-color: #58fe81;\n"
"    color: black;\n"
"    border: 2px solid black;\n"
"}")
        self.op_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.op_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.op_left.setObjectName("op_left")
        self.nfs_e = QtWidgets.QPushButton(self.op_left)
        self.nfs_e.setGeometry(QtCore.QRect(0, 50, 201, 23))
        self.nfs_e.setStyleSheet("QPushButton:hover {\n"
"    background-color: #58fe81;\n"
"    color: black;\n"
"    border: 2px solid rgb(60,60,60);\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: #58fe81;\n"
"    color: black;\n"
"    border: 2px solid black;\n"
"}")
        self.nfs_e.setObjectName("nfs_e")
        self.nfce = QtWidgets.QPushButton(self.op_left)
        self.nfce.setGeometry(QtCore.QRect(0, 90, 201, 23))
        self.nfce.setStyleSheet("")
        self.nfce.setObjectName("nfce")
        self.nfe = QtWidgets.QPushButton(self.op_left)
        self.nfe.setGeometry(QtCore.QRect(0, 130, 201, 23))
        self.nfe.setStyleSheet("")
        self.nfe.setObjectName("nfe")
        self.nf_devo = QtWidgets.QPushButton(self.op_left)
        self.nf_devo.setGeometry(QtCore.QRect(0, 170, 201, 23))
        self.nf_devo.setStyleSheet("")
        self.nf_devo.setObjectName("nf_devo")
        self.s_eng = QtWidgets.QPushButton(self.op_left)
        self.s_eng.setGeometry(QtCore.QRect(0, 470, 201, 23))
        self.s_eng.setStyleSheet("")
        self.s_eng.setObjectName("s_eng")
        self.bug_eng = QtWidgets.QPushButton(self.op_left)
        self.bug_eng.setGeometry(QtCore.QRect(0, 510, 201, 23))
        self.bug_eng.setStyleSheet("")
        self.bug_eng.setObjectName("bug_eng")
        self.d_relatorio = QtWidgets.QPushButton(self.op_left)
        self.d_relatorio.setGeometry(QtCore.QRect(0, 550, 201, 23))
        self.d_relatorio.setStyleSheet("")
        self.d_relatorio.setObjectName("d_relatorio")
        self.imp_etiqueta = QtWidgets.QPushButton(self.op_left)
        self.imp_etiqueta.setGeometry(QtCore.QRect(0, 590, 201, 23))
        self.imp_etiqueta.setStyleSheet("")
        self.imp_etiqueta.setObjectName("imp_etiqueta")
        self.modulo_fiscal = QtWidgets.QLabel(self.op_left)
        self.modulo_fiscal.setGeometry(QtCore.QRect(10, 9, 181, 31))
        self.modulo_fiscal.setAlignment(QtCore.Qt.AlignCenter)
        self.modulo_fiscal.setObjectName("modulo_fiscal")
        self.problemas = QtWidgets.QLabel(self.op_left)
        self.problemas.setGeometry(QtCore.QRect(5, 420, 191, 31))
        self.problemas.setAlignment(QtCore.Qt.AlignCenter)
        self.problemas.setObjectName("problemas")
        self.nf_remessa = QtWidgets.QPushButton(self.op_left)
        self.nf_remessa.setGeometry(QtCore.QRect(0, 210, 201, 23))
        self.nf_remessa.setStyleSheet("")
        self.nf_remessa.setObjectName("nf_remessa")
        self.nf_troca = QtWidgets.QPushButton(self.op_left)
        self.nf_troca.setGeometry(QtCore.QRect(-1, 250, 201, 23))
        self.nf_troca.setStyleSheet("")
        self.nf_troca.setObjectName("nf_troca")
        self.nf_cancela = QtWidgets.QPushButton(self.op_left)
        self.nf_cancela.setGeometry(QtCore.QRect(0, 290, 201, 23))
        self.nf_cancela.setStyleSheet("")
        self.nf_cancela.setObjectName("nf_cancela")
        self.banco_c = QtWidgets.QPushButton(self.op_left)
        self.banco_c.setGeometry(QtCore.QRect(0, 630, 201, 23))
        self.banco_c.setStyleSheet("")
        self.banco_c.setObjectName("banco_c")
        self.reinstall_0 = QtWidgets.QPushButton(self.op_left)
        self.reinstall_0.setGeometry(QtCore.QRect(0, 670, 201, 23))
        self.reinstall_0.setStyleSheet("")
        self.reinstall_0.setObjectName("reinstall_0")
        self.retro = QtWidgets.QPushButton(self.op_left)
        self.retro.setGeometry(QtCore.QRect(0, 330, 201, 23))
        self.retro.setStyleSheet("")
        self.retro.setObjectName("retro")
        self.portal_c = QtWidgets.QPushButton(self.op_left)
        self.portal_c.setGeometry(QtCore.QRect(0, 710, 201, 23))
        self.portal_c.setStyleSheet("")
        self.portal_c.setObjectName("portal_c")
        self.horizontalLayout.addWidget(self.op_left)
        self.Registro_area = QtWidgets.QFrame(self.content)
        self.Registro_area.setMaximumSize(QtCore.QSize(450, 16777215))
        self.Registro_area.setStyleSheet("#Registro_area Qframe{\n"
"    background:#3a3668;\n"
"}\n"
"#Registro_area QLineEdit {\n"
"    border:2px solid rgb(45,45,45);\n"
"    border-radius:5px;\n"
"    padding:15px;\n"
"    background-color:#ffffff;\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"#Registro_area QLineEdit:hover{\n"
"    border: 2px solid rgb(60,60,60);\n"
"}\n"
"#Registro_area QLineEdit:focus{\n"
"    border: 2px solid #58fe81;\n"
"}\n"
"\n"
"#Registro_area QPushButton{\n"
"    color: rgb(100, 100, 100);\n"
"    background-color:#ffffff;\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"}\n"
"#Registro_area QPushButton:hover {\n"
"    background-color: #58fe81;\n"
"    border: 2px solid rgb(60,60,60);\n"
"}\n"
"#Registro_area QPushButton:pressed {\n"
"    background-color: #58fe81;\n"
"    border: 2px solid #ff29e2;\n"
"}")
        self.Registro_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Registro_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Registro_area.setObjectName("Registro_area")
        self.lineEdit_Ncliente = QtWidgets.QLineEdit(self.Registro_area)
        self.lineEdit_Ncliente.setGeometry(QtCore.QRect(107, 295, 241, 51))
        self.lineEdit_Ncliente.setStyleSheet("\n""")
        self.lineEdit_Ncliente.setObjectName("lineEdit_Ncliente")

        self.pushButton_Copiar = QtWidgets.QPushButton(self.Registro_area)
        self.pushButton_Copiar.setGeometry(QtCore.QRect(107, 580, 241, 41))
        self.pushButton_Copiar.setStyleSheet("")
        self.pushButton_Copiar.setObjectName("pushButton_Copiar")

        self.lineEdit_CNPJ = QtWidgets.QLineEdit(self.Registro_area)
        self.lineEdit_CNPJ.setGeometry(QtCore.QRect(108, 358, 241, 51))
        self.lineEdit_CNPJ.setStyleSheet("")
        self.lineEdit_CNPJ.setObjectName("lineEdit_CNPJ")

        self.lineEdit_Telefone = QtWidgets.QLineEdit(self.Registro_area)
        self.lineEdit_Telefone.setGeometry(QtCore.QRect(108, 430, 241, 51))
        self.lineEdit_Telefone.setStyleSheet("")
        self.lineEdit_Telefone.setObjectName("lineEdit_Telefone")

        self.lineEdit_Protocolo = QtWidgets.QLineEdit(self.Registro_area)
        self.lineEdit_Protocolo.setGeometry(QtCore.QRect(108, 500, 241, 51))
        self.lineEdit_Protocolo.setStyleSheet("")
        self.lineEdit_Protocolo.setObjectName("lineEdit_Protocolo")
        self.super_maqp = QtWidgets.QFrame(self.Registro_area)
        self.super_maqp.setGeometry(QtCore.QRect(121, 80, 211, 170))
        self.super_maqp.setStyleSheet("background: url(:/background/maqq1.png);\n""background-repeat: no-repeat;\n""\n""")
        self.super_maqp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.super_maqp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.super_maqp.setObjectName("super_maqp")

        self.Titulo = QtWidgets.QFrame(self.Registro_area)
        self.Titulo.setGeometry(QtCore.QRect(140, 50, 171, 31))
        self.Titulo.setStyleSheet("background: url(:/background/tickethelp.png);\n""background-repeat: no-repeat;")
        self.Titulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Titulo.setObjectName("Titulo")

        self.pushButton_Salvar = QtWidgets.QPushButton(self.Registro_area)
        self.pushButton_Salvar.setGeometry(QtCore.QRect(109, 700, 241, 41))
        self.pushButton_Salvar.setStyleSheet("")
        self.pushButton_Salvar.setObjectName("pushButton_Salvar")
        self.pushButton_Direcionar = QtWidgets.QPushButton(self.Registro_area)
        self.pushButton_Direcionar.setGeometry(QtCore.QRect(350, 700, 21, 21))
        self.pushButton_Direcionar.setStyleSheet("QPushButton{\n""background-image: url(:/background/folder.svg);\n""")
        self.pushButton_Direcionar.setText("")
        self.pushButton_Direcionar.setObjectName("pushButton_Direcionar")
        self.horizontalLayout.addWidget(self.Registro_area)
        self.op_right = QtWidgets.QFrame(self.content)
        self.op_right.setMaximumSize(QtCore.QSize(200, 16777215))
        self.op_right.setStyleSheet("#op_right QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#op_right QPushButton {\n"
"    font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background: #141414;\n"
"}\n"
"#op_right QPushButton:hover {\n"
"    background-color: #58fe81;\n"
"    color: black;\n"
"    border: 2px solid rgb(60,60,60);\n"
"}\n"
"#op_right QPushButton:focus {\n"
"    background-color: #58fe81;\n"
"    color: black;\n"
"    border: 2px solid black;\n"
"}")
        self.op_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.op_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.op_right.setObjectName("op_right")
        self.reinstall_bk = QtWidgets.QPushButton(self.op_right)
        self.reinstall_bk.setGeometry(QtCore.QRect(0, 550, 201, 23))
        self.reinstall_bk.setStyleSheet("")
        self.reinstall_bk.setObjectName("reinstall_bk")
        self.certificado = QtWidgets.QPushButton(self.op_right)
        self.certificado.setGeometry(QtCore.QRect(0, 460, 201, 23))
        self.certificado.setStyleSheet("")
        self.certificado.setObjectName("certificado")
        self.ex_xml = QtWidgets.QPushButton(self.op_right)
        self.ex_xml.setGeometry(QtCore.QRect(0, 490, 201, 23))
        self.ex_xml.setStyleSheet("")
        self.ex_xml.setObjectName("ex_xml")
        self.v_relatorio = QtWidgets.QPushButton(self.op_right)
        self.v_relatorio.setGeometry(QtCore.QRect(0, 520, 201, 23))
        self.v_relatorio.setStyleSheet("")
        self.v_relatorio.setObjectName("v_relatorio")
        self.h_config = QtWidgets.QPushButton(self.op_right)
        self.h_config.setGeometry(QtCore.QRect(0, 130, 201, 23))
        self.h_config.setStyleSheet("")
        self.h_config.setObjectName("h_config")
        self.erro_abertura = QtWidgets.QPushButton(self.op_right)
        self.erro_abertura.setGeometry(QtCore.QRect(0, 50, 201, 23))
        self.erro_abertura.setStyleSheet("")
        self.erro_abertura.setObjectName("erro_abertura")
        self.erro_ex = QtWidgets.QPushButton(self.op_right)
        self.erro_ex.setGeometry(QtCore.QRect(0, 90, 201, 23))
        self.erro_ex.setStyleSheet("")
        self.erro_ex.setObjectName("erro_ex")
        self.h_perm = QtWidgets.QPushButton(self.op_right)
        self.h_perm.setGeometry(QtCore.QRect(0, 170, 201, 23))
        self.h_perm.setStyleSheet("")
        self.h_perm.setObjectName("h_perm")
        self.configuracao = QtWidgets.QLabel(self.op_right)
        self.configuracao.setGeometry(QtCore.QRect(4, 10, 190, 31))
        self.configuracao.setAlignment(QtCore.Qt.AlignCenter)
        self.configuracao.setObjectName("configuracao")
        self.casual = QtWidgets.QLabel(self.op_right)
        self.casual.setGeometry(QtCore.QRect(11, 412, 190, 31))
        self.casual.setAlignment(QtCore.Qt.AlignCenter)
        self.casual.setObjectName("casual")
        self.att_sistema = QtWidgets.QPushButton(self.op_right)
        self.att_sistema.setGeometry(QtCore.QRect(0, 580, 201, 23))
        self.att_sistema.setStyleSheet("")
        self.att_sistema.setObjectName("att_sistema")
        self.new_terminal = QtWidgets.QPushButton(self.op_right)
        self.new_terminal.setGeometry(QtCore.QRect(0, 610, 201, 23))
        self.new_terminal.setStyleSheet("")
        self.new_terminal.setObjectName("new_terminal")
        self.tc_servidor = QtWidgets.QPushButton(self.op_right)
        self.tc_servidor.setGeometry(QtCore.QRect(0, 640, 201, 23))
        self.tc_servidor.setStyleSheet("")
        self.tc_servidor.setObjectName("tc_servidor")
        self.tc_srv_central = QtWidgets.QPushButton(self.op_right)
        self.tc_srv_central.setGeometry(QtCore.QRect(0, 670, 201, 23))
        self.tc_srv_central.setStyleSheet("")
        self.tc_srv_central.setObjectName("tc_srv_central")
        self.treinamento = QtWidgets.QPushButton(self.op_right)
        self.treinamento.setGeometry(QtCore.QRect(0, 700, 201, 23))
        self.treinamento.setStyleSheet("")
        self.treinamento.setObjectName("treinamento")
        self.cd_cfop = QtWidgets.QPushButton(self.op_right)
        self.cd_cfop.setGeometry(QtCore.QRect(0, 730, 201, 23))
        self.cd_cfop.setStyleSheet("")
        self.cd_cfop.setObjectName("cd_cfop")
        self.open_guia = QtWidgets.QPushButton(self.op_right)
        self.open_guia.setGeometry(QtCore.QRect(0, 370, 201, 23))
        self.open_guia.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 75 italic 8pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.open_guia.setObjectName("open_guia")
        self.open_folder_instaladores = QtWidgets.QPushButton(self.op_right)
        self.open_folder_instaladores.setGeometry(QtCore.QRect(0, 340, 21, 21))
        self.open_folder_instaladores.setStyleSheet("QPushButton{\n"
"    \n"
"    background-image: url(:/Close_image/tools.svg);\n""}")
        self.open_folder_instaladores.setText("")
        self.open_folder_instaladores.setObjectName("open_folder_instaladores")
        self.open_folder_insumos = QtWidgets.QPushButton(self.op_right)
        self.open_folder_insumos.setGeometry(QtCore.QRect(30, 330, 29, 30))
        self.open_folder_insumos.setStyleSheet("QPushButton{\n"
"    \n"
"    background-image: url(:/Close_image/debug.svg);\n"
"    color: rgb(100, 100, 100);\n"
"    background-color:#ffffff;\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 15px;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #58fe81;\n"
"    border: 2px solid rgb(60,60,60);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #58fe81;\n"
"    border: 2px solid #ff29e2;\n"
"}")
        self.open_folder_insumos.setText("")
        self.open_folder_insumos.setObjectName("open_folder_insumos")
        self.horizontalLayout.addWidget(self.op_right)
        self.verticalLayout.addWidget(self.content)
        self.botton_bar = QtWidgets.QFrame(self.centralwidget)
        self.botton_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.botton_bar.setStyleSheet("border-radius: 0px;\n""background: #212220;\n""")
        self.botton_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.botton_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.botton_bar.setObjectName("botton_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.botton_bar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_credit = QtWidgets.QLabel(self.botton_bar)
        self.label_credit.setStyleSheet("color: #7f7a7a;")
        self.label_credit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credit.setObjectName("label_credit")
        self.verticalLayout_2.addWidget(self.label_credit)
        self.verticalLayout.addWidget(self.botton_bar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nfs_e.setText(_translate("MainWindow", "Auxilio NFS-e"))
        self.nfce.setText(_translate("MainWindow", "Auxilio NFC-e"))
        self.nfe.setText(_translate("MainWindow", "Auxilio NF-e"))
        self.nf_devo.setText(_translate("MainWindow", "NF-e Devolução"))
        self.s_eng.setText(_translate("MainWindow", "Solicitação Engenharia"))
        self.bug_eng.setText(_translate("MainWindow", "Bug Engenharia"))
        self.d_relatorio.setText(_translate("MainWindow", "Divergencia Relatório"))
        self.imp_etiqueta.setText(_translate("MainWindow", "Impressora de Etiquetas"))
        self.modulo_fiscal.setText(_translate("MainWindow", "Módulo Fiscal"))
        self.problemas.setText(_translate("MainWindow", "Problemas"))
        self.nf_remessa.setText(_translate("MainWindow", "NF-e Remessa"))
        self.nf_troca.setText(_translate("MainWindow", "NF-e Troca"))
        self.nf_cancela.setText(_translate("MainWindow", "Cancelar Nota"))
        self.banco_c.setText(_translate("MainWindow", "Banco Corrompido"))
        self.reinstall_0.setText(_translate("MainWindow", "Reinstalação do 0"))
        self.retro.setText(_translate("MainWindow", "Retroativa"))
        self.portal_c.setText(_translate("MainWindow", "Portal Contador"))
        self.lineEdit_Ncliente.setText(_translate("MainWindow", "Nome Cliente"))
        self.pushButton_Copiar.setText(_translate("MainWindow", "Copiar"))
        self.lineEdit_CNPJ.setText(_translate("MainWindow", "CNPJ"))
        self.lineEdit_Telefone.setText(_translate("MainWindow", "Telefone"))
        self.lineEdit_Protocolo.setText(_translate("MainWindow", "Protocolo"))
        self.pushButton_Salvar.setText(_translate("MainWindow", "Salvar"))
        self.reinstall_bk.setText(_translate("MainWindow", "Reinstalação com BK"))
        self.certificado.setText(_translate("MainWindow", "Certificado Digital"))
        self.ex_xml.setText(_translate("MainWindow", "Extrair XML"))
        self.v_relatorio.setText(_translate("MainWindow", "Visualizar Relatório"))
        self.h_config.setText(_translate("MainWindow", "Habilitar Configuração"))
        self.erro_abertura.setText(_translate("MainWindow", "Erro Abertura do Sistema"))
        self.erro_ex.setText(_translate("MainWindow", "Erro Extrair XML"))
        self.h_perm.setText(_translate("MainWindow", "Habilitar Permissão"))
        self.configuracao.setText(_translate("MainWindow", "Configuração"))
        self.casual.setText(_translate("MainWindow", "Casual"))
        self.att_sistema.setText(_translate("MainWindow", "Atualiazação Sistema"))
        self.new_terminal.setText(_translate("MainWindow", "Novo terminal"))
        self.tc_servidor.setText(_translate("MainWindow", "Troca Servidor"))
        self.tc_srv_central.setText(_translate("MainWindow", "Troca Servidor para Central"))
        self.treinamento.setText(_translate("MainWindow", "Treinamento rápido"))
        self.cd_cfop.setText(_translate("MainWindow", "Cadastro CFOP"))
        self.open_guia.setText(_translate("MainWindow", "Abrir 5 Guias Perfex"))
        self.label_credit.setText(_translate("MainWindow", "Created by: Herberth Amorim"))
import file_rc_rc
